"""Add access_logs and update locker_permissions for hybrid auth

Revision ID: 85cd5f3c6911
Revises: d9d47d10f5a9
Create Date: 2026-03-24 15:33:27.916235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cd5f3c6911'
down_revision: Union[str, Sequence[str], None] = 'd9d47d10f5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locker_id', sa.Integer(), nullable=True),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('can_open', sa.Boolean(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['locker_id'], ['lockers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_card_id'), 'access_logs', ['card_id'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_access_logs_user_id'), 'access_logs', ['user_id'], unique=False)
    op.add_column('locker_permissions', sa.Column('subject_type', sa.String(), nullable=False))
    op.add_column('locker_permissions', sa.Column('user_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('unique_role_locker'), 'locker_permissions', type_='unique')
    op.create_index(op.f('ix_locker_permissions_user_id'), 'locker_permissions', ['user_id'], unique=False)
    op.create_unique_constraint('unique_permission_target', 'locker_permissions', ['locker_id', 'role_name', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_permission_target', 'locker_permissions', type_='unique')
    op.drop_index(op.f('ix_locker_permissions_user_id'), table_name='locker_permissions')
    op.create_unique_constraint(op.f('unique_role_locker'), 'locker_permissions', ['role_name', 'locker_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('locker_permissions', 'user_id')
    op.drop_column('locker_permissions', 'subject_type')
    op.drop_index(op.f('ix_access_logs_user_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_card_id'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
