"""initial migration

Revision ID: d9d47d10f5a9
Revises: 
Create Date: 2026-02-05 15:32:22.632801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d47d10f5a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locker_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('can_view', sa.Boolean(), nullable=True),
    sa.Column('can_open', sa.Boolean(), nullable=True),
    sa.Column('can_edit', sa.Boolean(), nullable=True),
    sa.Column('can_take', sa.Boolean(), nullable=True),
    sa.Column('can_manage', sa.Boolean(), nullable=True),
    sa.Column('valid_until', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('locker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['locker_id'], ['lockers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name', 'locker_id', name='unique_role_locker')
    )
    op.create_index(op.f('ix_locker_permissions_id'), 'locker_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_locker_permissions_role_name'), 'locker_permissions', ['role_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locker_permissions_role_name'), table_name='locker_permissions')
    op.drop_index(op.f('ix_locker_permissions_id'), table_name='locker_permissions')
    op.drop_table('locker_permissions')
    # ### end Alembic commands ###
